
debug: false

logging:
  level:
    org.apache.camel: INFO
    org.apache.camel.cloud: DEBUG
    org.apache.camel.component.kubernetes: DEBUG

camel:
  springboot:
    main-run-controller: true
    name: CamelBoot
  cloud:
    kubernetes:
      service-discovery:
        enabled: true
        lookup: dnssrv
        dns-domain: cluster.local
        port-name: http
        port-protocol: tcp
